image: node:16.17.0

stages:
  - deploy
  # - artifacts

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - front-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  echo -e "\nSELF_DOMAIN_NAME=''" >> .env; else echo -e "\nSELF_DOMAIN_NAME=-$CI_COMMIT_REF_NAME" >> .env;  fi;
    - cat .env
    - ls -las
    - pwd
    - sed 's/servername/'"$CI_COMMIT_REF_NAME"'/g' docker-compose.yaml >docker-compose-updated.yaml
    - cat docker-compose-updated.yaml
  script:
    - docker-compose -f docker-compose-updated.yaml up -d --build
# artifacts:
#   stage: deploy
#   script:
#     - node -v
#     - npm -v
#     - npm config set registry http://registry.npm.taobao.org/
#     - npm install -g pnpm
#     - pnpm config set registry https://registry.npm.taobao.org/
#     - pnpm install
#     - pnpm run build
#   artifacts:
#     paths:
#       - dist/
#     exclude:
#       - node_modules/
#   cache:
#     when: on_success
#     key:
#       files:
#         - pnpm-lock.yaml
#         - package.json
#   only:
#     - main
#     - master
#   interruptible: true
